main: main.c string_dv.h string_dv.c
	gcc -I ./ string_dv.c main.c
	./a.out
debug: main.c string_dv.h string_dv.c
	gcc -g -I ./ string_dv.c main.c
	gdb ./a.out
build: main.c string_dv.h string_dv.c
	gcc -I ./ string_dv.c main.c
